name: jobflex
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0  


  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1

  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  image_picker: ^1.0.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - img/
    - Icons/